{
 "title": "Sequoia Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "File count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sequoia_file_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Block height",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sequoia_block_height", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current Proof Processing",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 9, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sequoia_current_proofs_processing",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JKL Balance",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sequoia_balance", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "targets": [
    { "expr": "sequoia_queue_size", "legendFormat": "__auto" }
   ]
  }
 ]
}