name: End-to-end Test

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-go@v5
      - name: Install Venom
        shell: bash
        run: curl https://github.com/ovh/venom/releases/download/v1.2.0/venom.linux-amd64 -L -o /usr/local/bin/venom && chmod +x /usr/local/bin/venom
      - name: Test
        shell: bash
        working-directory: ./test
        run: venom run -vv e2e/init.yaml `find e2e/ -type f -name "*_test-*.yaml" | sort`

